# Generated by Django 3.2.6 on 2021-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("developers", "0007_alter_profile_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Slug"),
        ),
    ]
